insert into Clients values ('Jose Carlos', 'josecarlos@gmail.com')
insert into Clients values ('Abner Aparecido', 'abneraparecido@hotmail.com')
insert into Clients values ('Maria Constatino', 'mariac@gmail.com')
insert into Clients values ('Eduardo Batista', 'ebatista@gmail.com')
insert into Clients values ('Carla Peres', 'carlinha1@yahoo.com')
insert into Clients values ('ElTchan do Sambinha', 'eds@gmail.com')
insert into Clients values ('Thalita Vanessa', 'vanessa.t@gmail.com')
insert into Clients values ('Felipe Almeida', 'felipea@gmail.com')
insert into Clients values ('Kilda Case', 'kcase@gmail.com')
insert into Clients values ('José Ernandes', 'josee@gmail.com')
insert into Clients values ('Murilo Faria', 'murilofaria1998@gmail.com')
insert into Clients values ('José Mourinho', 'jjmourinho@gmail.com')
insert into Clients values ('Roberto Carlos', 'robertocarlos@gmail.com')
insert into Clients values ('Vagner Alencar', 'vagneralencar@gmail.com')
insert into Clients values ('Tio do Samba', 'tiodosamba@gmail.com')
insert into Clients values ('Bon Jovi', 'bonjovi@gmail.com')
insert into Clients values ('Cavaleiros do Zodiaco', 'cavalheiros@gmail.com')
insert into Clients values ('José Peralta', 'peraltinha@bol.com')
insert into Clients values ('Mara Maravilha', 'maradosbt@gmail.com')
insert into Clients values ('Xuxa Meneguel', 'xuxa01@gmail.com')
insert into Clients values ('Elizabeth Faria', 'elifa@gmail.com')
insert into Clients values ('Tania Alencar', 'tanicaalencar@gmail.com')
insert into Clients values ('Ronaldinho Gaucho', 'ronaldinho@gmail.com')
insert into Clients values ('Kaka', 'kaka@gmail.com')